spring:
  profiles:
    active: @profiles.active@

### 服务配置 ###
server:
  port: 10081
  session:
    timeout: 7200
  servlet:
    context-path: /ms/api
#  tomcat:
#    max-swallow-size: -1
#  max-http-header-size: 2MB

#env: stg
