spring:
  application:
    name: yizhentang
  profiles:
    active: @profiles.active@
  mvc:
    servlet:
      load-on-startup: 1
      multipart:
        max-file-size: 10MB     #单个文件最大限制
        max-request-size: 50MB  #多个文件最大限制


### 服务配置 ###
server:
  port: 10082
  session:
    timeout: 7200
  servlet:
    context-path: /hs/api


### mybatis ###
mybatis-plus:
  type-aliases-package: com.maizhiyu.yzt.entity
  mapper-locations: classpath*:/mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDel # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: auto