spring:
  profiles:
    active: @profiles.active@
  mvc:
    servlet:
      load-on-startup: 1

### 服务配置 ###
server:
  port: 10082
  session:
    timeout: 7200
  servlet:
    context-path: /hs/api


### 分页插件 ###
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
  params: count=countSql