### spring ###
spring:
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #     mysql驱动包
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.0.90:3306/yztdev?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: yzt123456
    druid:
      #      数据库连接池的最小维持连接数
      min-idle: 10
      #      初始化连接数
      initial-size: 20
      # 最大连接数
      max-active: 5000
      #      等待连接获取的最大超时时间
      max-wait: 60000
      #      有两个含义：
      #      1) Destroy线程会检测连接的间隔时间
      #      2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      time-between-eviction-runs-millis: 3000
      #      Destory线程中如果检测到当前连接的最后活跃时间和当前时间的差值大于
      #      minEvictableIdleTimeMillis，则关闭当前连接。
      min-evictable-idle-time-millis: 180000
      #      用来检测连接是否有效的sql，要求是一个查询语句。
      #      如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      validation-query: SELECT 'x'
      #      如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      #      申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      #      归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      #      是否缓存preparedStatement，也就是PSCache。
      #      PSCache对支持游标的数据库性能提升巨大，比如说oracle。
      #      在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。
      #      5.5及以上版本有PSCache，建议开启。
      pool-prepared-statements: true
      #      要启用PSCache，必须配置大于0，当大于0时，
      #      poolPreparedStatements自动触发修改为true。
      #      在Druid中，不会存在Oracle下PSCache占用内存过多的问题，
      #      可以把这个数值配置大一些，比如说100
      max-open-prepared-statements: 500
      #      指定连接建立多长时间就需要被强制关闭
      #      则它会自动转换成可利用的连接。默认的超时时间是300秒
      remove-abandoned-timeout: 180
      #      是否在自动回收超时连接的时候打印连接的超时错误
      log-abandoned: false
      #      监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
      filters: stat,log4j

  # redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 86400
    #password: 123456
  session:
    store-type: redis


### swagger ###（生产环境时需要关闭）
swagger:
  enable: true

### 业务配置 ###
file:
  upload-folder: /Users/huhu/Temps/static/
  static-access-path: /files/**

#
oss:
  endpoint: "oss-cn-hangzhou.aliyuncs.com"
  accessKeyId: "LTAI5tEozMaZFLJXmjtv2y1L"
  accessKeySecret: "DQtx7CwSvvrV3trwdaYEQRhhVAHCiw"
  publicBucket: "yzt-test-public"
  publicBucketUrl: "https://yzt-test-public.oss-cn-hangzhou.aliyuncs.com"
  privateBucket: "yzt-test-privacy"
  privateBucketUrl: "https://yzt-test-privacy.oss-cn-hangzhou.aliyuncs.com"
  expiration: "30"
  styleWatermark: "一真堂"
  styleMicro: "一真堂"


sms:
  endpoint: "dysmsapi.aliyuncs.com"
  accessKeyId: "LTAI5tMFpwTnAJLCBNgxjAQ7"
  accessKeySecret: "EZ0gRdDiP6QkvfGAfuJfxK57PEBr34"
  signName: "杭州一真医疗器械"


