spring:
  profiles:
    active: local



oss:
  endpoint: "oss-cn-hangzhou.aliyuncs.com"
  accessKeyId: "LTAI5tEozMaZFLJXmjtv2y1L"
  accessKeySecret: "DQtx7CwSvvrV3trwdaYEQRhhVAHCiw"
  publicBucket: "yzt-hs-dev"
  publicBucketUrl: "yzt-hs-dev.oss-cn-hangzhou.aliyuncs.com"
  privateBucket: "yzt-equipment"
  privateBucketUrl: "yzt-equipment.oss-cn-hangzhou.aliyuncs.com"
  expiration: "30"
  styleWatermark: "一真"
  styleMicro: "一真"
