spring:
  profiles:
    active: @profiles.active@
#    active: prod,utils-prod

### 服务配置 ###
server:
  port: 10084
  session:
    timeout: 7200
  servlet:
    context-path: /ps/api
#env: stg

mybatis-plus:
  type-aliases-package: com.maizhiyu.yzt.entity
  mapper-locations: classpath*:/mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl