### spring ###
spring:
  application:
    name: yizhentang
  http:
    multipart:
      max-file-size: 2000Mb      # Max file size，默认1M
      max-request-size: 2500Mb   # Max request size，默认10M
  datasource:
    #     mysql驱动包
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1xk4j7gsb2ylig3so.mysql.rds.aliyuncs.com:3306/yztdev?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: yztdev
    password: workDB1gfd@WSX
    druid:
      #      数据库连接池的最小维持连接数
      min-idle: 10
      #      初始化连接数
      initial-size: 20
      # 最大连接数
      max-active: 5000
      #      等待连接获取的最大超时时间
      max-wait: 60000
      #      有两个含义：
      #      1) Destroy线程会检测连接的间隔时间
      #      2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      time-between-eviction-runs-millis: 3000
      #      Destory线程中如果检测到当前连接的最后活跃时间和当前时间的差值大于
      #      minEvictableIdleTimeMillis，则关闭当前连接。
      min-evictable-idle-time-millis: 180000
      #      用来检测连接是否有效的sql，要求是一个查询语句。
      #      如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
      validation-query: SELECT 'x'
      #      如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      test-while-idle: true
      #      申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      #      归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-return: false
      #      是否缓存preparedStatement，也就是PSCache。
      #      PSCache对支持游标的数据库性能提升巨大，比如说oracle。
      #      在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。
      #      5.5及以上版本有PSCache，建议开启。
      pool-prepared-statements: true
      #      要启用PSCache，必须配置大于0，当大于0时，
      #      poolPreparedStatements自动触发修改为true。
      #      在Druid中，不会存在Oracle下PSCache占用内存过多的问题，
      #      可以把这个数值配置大一些，比如说100
      max-open-prepared-statements: 500
      #      指定连接建立多长时间就需要被强制关闭
      #      则它会自动转换成可利用的连接。默认的超时时间是300秒
      remove-abandoned-timeout: 180
      #      是否在自动回收超时连接的时候打印连接的超时错误
      log-abandoned: false
      #      监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
      filters: stat,wall,log4j

  # redis 配置
  redis:
    host: 127.0.0.1
    port: 6300
    password: yzt123456
    timeout: 86400
  session:
    store-type: redis

# 微信公众号配置
weixin:
  # token更新设置
  enable: true
  crontab: "0 0 */1 * * ?"
  # 微信基础信息
  # 公众号脉之语
  #  appid: wx770c893ff4f74c9a
  #  appsecret: ad183550a3205ffb22c9bf805263c0ad
  #  token: mzy18ljf61gk2801cgy451zsw3452by4
  # 公众号中医真知
  #  appid: wxbbf7c24f3dc46277
  #  appsecret: f8c2b9d05197df61ec28b12c43d0229c
  #  token: mzy18ljf61gk2801cgy451zsw3452by4
  # 公众号测试账号
  appid: wx201279a7616325aa
  appsecret: 9d92acd5a15f2f6a2fc3e36a1883e238
  token: huhutech
  # 授权相关信息
  auth_scope: snsapi_userinfo   # scope: snsapi_base
  api_domain: https://api.weixin.qq.com
  authorize_url: https://open.weixin.qq.com/connect/oauth2/authorize
  # 页面跳转信息
  redirect_url: http://klqlfnb.nat.ipyingshe.com/wx/api/wx/onCallback
  business_url: http://klqlfnb.nat.ipyingshe.com/ps/index.html
  # 腾讯位置服务
  location_domain: https://apis.map.qq.com
  location_path: /ws/geocoder/v1
  location_key: UZIBZ-E3CWK-O7GJ5-AZ5QE-5CFP7-ORFNL


### swagger ###（生产环境时需要关闭）
swagger:
  enable: true

### 业务配置 ###
file:
  upload-folder: /Users/huhu/Temps/static/
  static-access-path: /files/**
